### ISSUE TITLE
Make used UserAgent configurable

### ISSUE THREAD

**Issue by holtkamp** [dpovshed/octopus#1]
Nice project!

Currently [the used UserAgent is fixed](https://github.com/dpovshed/octopus/blob/c3f32e75f6874eee3e676ea34683340e2995e3cb/Octopus/Processor.php#L94), might be nice to make this configurable...

**Comment by muller** [comment]
👍

**Comment by dpovshed** [comment]
Sorry guys for not responding earlier! Surely, I would love to see useful updates of this project, and happy to see the new _develop_ branch and ongoing work there!

**Comment by holtkamp** [comment]
he @dpovshed my work on the [develop](https://github.com/holtkamp/octopus/tree/develop) branch has stabilised, I will review the documentation, etc. What shall I do, open a pull-request for the complete branch?

**Comment by dpovshed** [comment]
Hi @holtkamp !
I took a brief look at the code and have enough trust in you, so I added you as a 'collaborator' here on GitHub.

As far as I know, this should give you push access to my repository, so you can merge right in place.

I am not sure if these right are sufficient to do release or perform other advanced operations, but I hope this  should simplify your work.

Any questions or comments - just let me know!

**Comment by dpovshed** [comment]
https://github.com/dpovshed/octopus/invitations is the link to invitation

**Comment by holtkamp** [comment]
@dpovshed awesome! Will cleanup where required push it and tag a `0.1.0` 😄

**Comment by holtkamp** [comment]
done! https://github.com/dpovshed/octopus/releases/tag/0.1.0
