### ISSUE TITLE
Consider adopting mq-react to manage concurrency

### ISSUE THREAD

**Issue by holtkamp** [dpovshed/octopus#17]
It seems we could "outsource" the part that manages queuing in the TargetManager to https://github.com/clue/php-mq-react, this does increase the number of dependencies...

**Comment by dpovshed** [comment]
At a glance, the library looks nice. Not sure about 'fixing when it is not broken' :)

For me it is hard to evaluate how much lines of code we could save, without losing any functionality

**Comment by holtkamp** [comment]
As suggested in https://github.com/clue/reactphp-mq/issues/13#issuecomment-394108721, https://github.com/clue/reactphp-flux seems to be a better candidate for this. 

Just submitted https://github.com/dpovshed/octopus/pull/31

Closing this issue
