### ISSUE TITLE
Configure automatic updates on packagist.org

### ISSUE THREAD

**Issue by holtkamp** [dpovshed/octopus#44]
After this package has been registered at Packagist via https://github.com/dpovshed/octopus/issues/13 it might be useful to make sure new releases like https://github.com/dpovshed/octopus/releases/tag/0.8.0 automatically appear at https://packagist.org/packages/octopoda/octopus as described at https://packagist.org/about#how-to-update-packages

@dpovshed I tried to do this, but after connecting my GitHub account with packagist, this package does not show up in my packagist account, so I suppose only you can do that?

**Comment by dpovshed** [comment]
Thank you, I had just enabled this functionality!

And we have 0.8.0 on https://packagist.org/packages/octopoda/octopus ! :)
