### ISSUE TITLE
Prevent use of file_get_contents()

### ISSUE THREAD

**Issue by holtkamp** [dpovshed/octopus#6]
https://github.com/dpovshed/octopus/blob/ec11ba314f17a97d8a8fd27490bfd04dd2410372/src/TargetManager.php#L45

Apparently this is not allowed?

https://twitter.com/Fneufneu/status/890258282362941440

**Comment by kelunik** [comment]
Of course it's allowed. But it blocks and nothing can happen concurrently. As this is just the bootstrapping, it doesn't actually matter.

**Comment by dpovshed** [comment]
Guys, while in preparation phase using of file_get_contents is totally fine, I should confess that I also used file_put_contents in the Processor::onData() function.

So if anyone has the desire to speed up file operations, there is still a space for improvement and making the code more 'async-ish'.

**Comment by kelunik** [comment]
It's local filesystem access there, which is generally pretty fast. It's just fine. 

Blocking just means nothing can happen concurrently. It's not really a problem for client applications. It only matters for servers.

**Comment by dpovshed** [comment]
Thanks @kelunik for your input!

I believe we can close the ticket then.
