### ISSUE TITLE
Support more options

### ISSUE THREAD

**Issue by dpovshed** [dpovshed/octopus#7]
We had a bunch of nice options, but at the moment it seems only a _concurrency_ is supported. All others options still exist as member variables of the Config class, so this can be used as a specification.

Of course, some might be ineffective/obsolete, as well as new options could be introduced.

**Comment by dpovshed** [comment]
@holtkamp FYI - seems we had lost something :)

**Comment by dpovshed** [comment]
added _requestType_ and _timeout_ , more needs to come

**Comment by dpovshed** [comment]
I think we recovered all or almost all options, and even introduced a new one like presenter. Thus this could be closed now. What do you think @holtkamp ?

**Comment by holtkamp** [comment]
Yeah, sure! We can always add more when needed...

So closing now!
